[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  chris--a/Keypad
  rlogiacco/CircularBuffer
  sensorium/Mozzi@1.1.2
  https://github.com/max22-/ESP32-BLE-MIDI.git
build_flags = 
  -D LED_BUILTIN=2
